# Generated by Django 2.2.4 on 2019-08-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
