# Generated by Django 2.2.4 on 2019-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
